create table trabajador(seguro integer primary key, nombre varchar2(25), edad integer);
create table nomina(id_nomina integer, seguro integer, sueldo_base float, horas_laboradas integer, fecha_pago date, constraint pk_id_nomina primary key(id_nomina), 
constraint fk_seguro foreign key(seguro) references trabajador(seguro));

create sequence sec_nomina
start with 1
increment by 1
nomaxvalue;

CREATE OR REPLACE PROCEDURE GUARDAR_NOMINA(MY_ID_NOMINA OUT INTEGER, MY_SEGURO IN INTEGER, MY_SUELDO_BASE IN INTEGER)
AS 
BEGIN
SELECT SEC_NOMINA.NEXTVAL INTO MY_ID_NOMINA FROM DUAL;
INSERT INTO NOMINA(ID_NOMINA, SEGURO,SUELDO_BASE) VALUES(MY_ID_NOMINA, MY_SEGURO, MY_SUELDO_BASE);
END;
/

CREATE OR REPLACE PROCEDURE GENERAR_TRABAJADOR(MY_SEGURO IN INTEGER, MY_NOMBRE IN VARCHAR2, MY_EDAD IN INTEGER, MY_ID_NOMINA OUT INTEGER, MY_SUELDO_BASE IN FLOAT)
AS 
BEGIN
INSERT INTO TRABAJADOR VALUES(MY_SEGURO, MY_NOMBRE,MY_EDAD);
GUARDAR_NOMINA(MY_ID_NOMINA, MY_SEGURO, MY_SUELDO_BASE);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
GENERAR_TRABAJADOR(4,'Karla',41,VALOR,10000);
END;
/

SELECT * FROM TRABAJADOR;
SELECT * FROM NOMINA;

/

DECLARE CURSOR CUR_1 IS SELECT * FROM TRABAJADOR; 
BEGIN 
FOR REC IN CUR_1 LOOP 
dbms_output.put_line('NOMBRE '||REC.NOMBRE|| ' EDAD '||REC.EDAD); 
END LOOP; 
END; 
/

DECLARE 
CURSOR CUR_1 IS SELECT * FROM TRABAJADOR; 
CURSOR CUR_2 IS SELECT * FROM NOMINA;  
BEGIN 
FOR REC IN CUR_1 LOOP 
FOR REC2 IN CUR_2 LOOP 
IF REC2.SEGURO=REC.SEGURO THEN 
dbms_output.put_line('NOMBRE '||REC.NOMBRE||' EDAD '||REC.EDAD||' SUELDO BASE '|| REC2.SUELDO_BASE); 
END IF; 
END LOOP; 
END LOOP; 
END; 
/

SET SERVEROUTPUT ON; 

--GENERAR UN PROCEDIMIENTO ALMACENADO QUE EFECTUE UN UPDATE MASIVO, QUE HAGA LO SIGUIENTE 
--DEBERA ACTUALIZAR LAS HORAS LABORADAS A 40 PARA TODOS LOS TRABAJADORES Y DEBE IMPRIMIR LO SIGUIENTE 
--AL EFECTUAR LA INVOCACION DEL PROCEDIMIENTO 
-- NOMBRE  ANA    SUELDO  6000   HORAS   40 PAGO   240,000
------------------------------------------------------------------------------------------------------------
-----CURSORES CON UPDATE ----------------------------------------------------------------------------------

DECLARE 
CURSOR CUR_3 IS SELECT * FROM NOMINA FOR UPDATE; 
BEGIN 
FOR REC IN CUR_3 LOOP 
UPDATE NOMINA SET HORAS_LABORADAS=40 WHERE CURRENT OF CUR_3; 
END LOOP; 
END; 
/
